###
GET http://127.0.0.1:3000/
Accept: application/json
###
GET http://127.0.0.1:3000/db/health
Accept: application/json
###
GET http://127.0.0.1:3000/engine/info
Accept: application/json
###
GET http://127.0.0.1:3000/session/info
Accept: application/json
###